background 232136
foreground e0def4
cursor e0def4
cursor_text_color 232136
selection_background #6E6A86
selection_foreground #E0DEF4
color0 #191724
color1 #EB6F92
color2 #C4A7E7
color3 #EBBCBA
color4 #9CCFD8
color5 #C4A7E7
color6 #EBBCBA
color7 #E0DEF4
color8 #6E6A86
color9 #EB6F92
color10 #C4A7E7
color11 #EBBCBA
color12 #9CCFD8
color13 #C4A7E7
color14 #6E6A86
color15 #C4A7E7
