dofile(os.getenv("HOME") .. "/.config/hypr/bind.lua")

-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

--

-- autogenerated = 1 # remove this line to remove the warning

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "LVDS-1",
    mode     = "1366x768",
    position = "0x0",
    scale    = 1,
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch







-- exec-once = sh ~/.config/hypr/scripts/nogaps.sh

-- exec-once = swayidle -w timeout 300 'swaylock -f' timeout 600 'sleep' before-sleep 'swaylock -f' 

-- Source a file (multi-file configs)

-- source = ~/.config/hypr/bind.conf -> requires manual conversion
-- local bind = require("bind")
-- TODO: convert ~/.config/hypr/bind.conf to .lua and use require()

-- Some default env vars.

hl.env("XCURSOR_SIZE", 2)

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "us",
        numlock_by_default = true,
        follow_mouse = 1,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            disable_while_typing = true,
        },
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        -- HYPR056-DISABLED:     no_border_on_floating = true
        layout = "dwindle",
        col = {
            active_border = "0xffcba6f7",
            inactive_border = "0xff313244",
        },
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 5,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 10,
            passes = 1,
            new_optimizations = true,
        },
        shadow = {
            enabled = true,
            -- HYPR056-DISABLED:         ignore_window = true
            range = 4,
            offset = "2 2",
            render_power = 2,
            color = "0x66000000",
        },
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring>
    },
})
hl.curve("myBezier", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "default" })

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        -- HYPR056-DISABLED:     pseudotile = true # master switch for pseudotiling. Enabling is boun>
        preserve_split = true,
        -- you probably want this
    },
})

hl.config({
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_status = "master",
        new_on_top = true,
    },
})

hl.config({
    gestures = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        -- HYPR056-DISABLED:     workspace_swipe = true
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more

-- device:epic-mouse-v1 {

--     sensitivity = -0.5

-- }

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- HYPR056-OLD-RULE: windowrulev2 = float, class:floating

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- dracula/hyprland

hl.config({
    general = {
        --col.active_border = rgb(44475a) rgb(bd93f9) 90deg
        --col.inactive_border = rgba(44475aaa)
        --col.group_border = rgba(282a36dd)
        --col.group_border_active = rgb(bd93f9) rgb(44475a) 90deg
        -- non-gradient alternative
        --col.active_border = rgb(bd93f9)
        --col.inactive_border = rgba(44475aaa)
        --col.group_border = rgba(282a36dd)
        --col.group_border_active = rgb(bd93f9)
        -- rgb(6272a4) # or rgb(44475a)
        -- col.nogroup_border = rgb(282a36)
        -- col.nogroup_border_active = rgb(6272a4) # or rgb(44475a)
        col = {
            active_border = "rgb(268bd2)",
            inactive_border = "rgb(1a1a1a)",
        },
    },
})

-- Window rules

-- HYPR056-OLD-RULE:   windowrule = float, class:file_progress

-- HYPR056-OLD-RULE:   windowrule = float, class:confirm

-- HYPR056-OLD-RULE:   windowrule = float, class:dialog

-- HYPR056-OLD-RULE:   windowrule = float, class:download

-- HYPR056-OLD-RULE:   windowrule = float, class:notification

-- HYPR056-OLD-RULE:   windowrule = float, class:error

-- HYPR056-OLD-RULE:   windowrule = float, class:splash

-- HYPR056-OLD-RULE:   windowrule = float, class:confirmreset

-- HYPR056-OLD-RULE:   windowrule = float, title:Open File

-- HYPR056-OLD-RULE:   windowrule = float, title:branchdialog

-- HYPR056-OLD-RULE:   windowrule = float, class:zoom

--   windowrule = fullscreen, vlc

-- HYPR056-OLD-RULE:   windowrule = float, class:Lxappearance

-- HYPR056-OLD-RULE:   windowrule = float, class:ncmpcpp

-- HYPR056-OLD-RULE:   windowrule = float, class:Rofi

-- HYPR056-OLD-RULE:   windowrule = animation none, class:Rofi

-- HYPR056-OLD-RULE:   windowrule = float, class:viewnior

-- HYPR056-OLD-RULE:   windowrule = float, class:pavucontrol-qt

-- HYPR056-OLD-RULE:   windowrule = float, class:gucharmap

-- HYPR056-OLD-RULE:   windowrule = float, class:gnome-font

-- HYPR056-OLD-RULE:   windowrule = float, class:org.gnome.Settings

-- HYPR056-OLD-RULE:   windowrule = float, class:file-roller

-- HYPR056-OLD-RULE:   windowrule = float, class:nautilus

-- HYPR056-OLD-RULE:   windowrule = float, class:nemo

-- HYPR056-OLD-RULE:   windowrule = float, class:thunar

-- HYPR056-OLD-RULE:   windowrule = float, class:Pcmanfm

--   windowrule = float, obs

-- HYPR056-OLD-RULE:   windowrule = float, class:wdisplays

-- HYPR056-OLD-RULE:   windowrule = float, class:zathura

-- HYPR056-OLD-RULE:   windowrule = float, class:*.exe

-- HYPR056-OLD-RULE:   windowrule = fullscreen, class:wlogout

-- HYPR056-OLD-RULE:   windowrule = float, title:wlogout

-- HYPR056-OLD-RULE:   windowrule = fullscreen, title:wlogout

-- HYPR056-OLD-RULE:   windowrule = float, class:pavucontrol-qt

-- HYPR056-OLD-RULE:   windowrule = float, class:keepassxc

-- HYPR056-OLD-RULE:   windowrule = idleinhibit focus, class:mpv

-- HYPR056-OLD-RULE:   windowrule = idleinhibit fullscreen, class:firefox

-- HYPR056-OLD-RULE:   windowrule = float, title:^(Media viewer)$

-- HYPR056-OLD-RULE:   windowrule = float, title:^(Transmission)$

-- HYPR056-OLD-RULE:   windowrule = float, title:^(Volume Control)$

-- HYPR056-OLD-RULE:   windowrule = float, title:^(Picture-in-Picture)$

-- HYPR056-OLD-RULE:   windowrule = float, title:^(Firefox — Sharing Indicator)$

-- HYPR056-OLD-RULE:   windowrule = move 0 0, title:^(Firefox — Sharing Indicator)$

-- HYPR056-OLD-RULE:   windowrule = size 800 600, title:^(Volume Control)$

-- HYPR056-OLD-RULE:   windowrule = move 75 44%, title:^(Volume Control)$

-- windowrulev2 = opacity 0.85 0.85,class:^(Alacritty|code-oss)$

-- https://github.com/hyprwm/Hyprland/issues/2412

-- HYPR056-OLD-RULE:   windowrulev2=nofocus,class:^jetbrains-(?!toolbox),floating:1,title:^win\d+$

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("dunst -conf ~/.config/dunst/dunstrc")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("hypridle")
end)
