local mod = "SUPER"

--[[
Key rebinds. rebinds.lua is generated by the Hub's Keybinds page (Ryoku Settings)
and maps a shipped chord to a user-chosen one, e.g. { ["SUPER + Q"] = "SUPER + X" }.
K() wraps every bind's key argument, so a rebind is a pure key swap: the default
chord is simply never registered and the dispatcher never moves. Absent or
malformed, K() is the identity and every shortcut keeps its shipped default.
]]
local ok, rebinds = pcall(require, "rebinds")
if not ok or type(rebinds) ~= "table" then rebinds = {} end
local function K(k) return rebinds[k] or k end

-- Windows
hl.bind(K(mod .. " + Q"),         hl.dsp.window.close())                           -- close active window
hl.bind(K(mod .. " + F"),         hl.dsp.window.fullscreen())                      -- fullscreen
hl.bind(K(mod .. " + A"),         function() hl.dispatch(hl.dsp.window.float({ action = "toggle" })); hl.dispatch(hl.dsp.window.resize({ x = 1000, y = 660, exact = true })); hl.dispatch(hl.dsp.window.center()) end) -- float at 1000x660, centred (press again to tile back)
hl.bind(K(mod .. " + R"),         function() hl.dispatch(hl.dsp.submap("resize")); hl.dispatch(hl.dsp.exec_cmd("hyprctl notify -1 2200 0 'Resize mode: arrows or hjkl resize, Esc exits'")) end) -- resize mode (arrows/hjkl resize, Esc exits)
hl.bind(K(mod .. " + P"),         hl.dsp.exec_cmd("ryoku-monitor toggle"))         -- mirror <-> extend displays

-- Focus and move windows
hl.bind(K(mod .. " + Left"),          hl.dsp.focus({ direction = "left" }))        -- focus left
hl.bind(K(mod .. " + Right"),         hl.dsp.focus({ direction = "right" }))       -- focus right
hl.bind(K(mod .. " + Up"),            hl.dsp.focus({ direction = "up" }))          -- focus up
hl.bind(K(mod .. " + Down"),          hl.dsp.focus({ direction = "down" }))        -- focus down
hl.bind(K(mod .. " + SHIFT + Left"),  hl.dsp.window.move({ direction = "left" }))  -- move window left
hl.bind(K(mod .. " + SHIFT + Right"), hl.dsp.window.move({ direction = "right" })) -- move window right
hl.bind(K(mod .. " + SHIFT + Up"),    hl.dsp.window.move({ direction = "up" }))    -- move window up
hl.bind(K(mod .. " + SHIFT + Down"),  hl.dsp.window.move({ direction = "down" }))  -- move window down
hl.bind(K(mod .. " + CTRL + Left"),   hl.dsp.window.resize({ x = -40, y = 0,   relative = true }), { repeating = true }) -- resize window narrower
hl.bind(K(mod .. " + CTRL + Right"),  hl.dsp.window.resize({ x = 40,  y = 0,   relative = true }), { repeating = true }) -- resize window wider
hl.bind(K(mod .. " + CTRL + Up"),     hl.dsp.window.resize({ x = 0,   y = -40, relative = true }), { repeating = true }) -- resize window shorter
hl.bind(K(mod .. " + CTRL + Down"),   hl.dsp.window.resize({ x = 0,   y = 40,  relative = true }), { repeating = true }) -- resize window taller

-- Apps
hl.bind(K(mod .. " + Return"),    hl.dsp.exec_cmd("ryoku-app terminal"))           -- terminal
hl.bind(K(mod .. " + E"),         hl.dsp.exec_cmd("ryoku-app files"))              -- file manager
hl.bind(K(mod .. " + B"),         hl.dsp.exec_cmd("ryoku-app browser"))            -- browser
hl.bind(K(mod .. " + N"),         hl.dsp.exec_cmd("ryoku-app editor"))             -- editor
hl.bind(K(mod .. " + O"),         hl.dsp.exec_cmd("ryoku-app notes"))              -- notes
hl.bind(K(mod .. " + ALT + E"),   hl.dsp.exec_cmd("kitty -e yazi"))               -- yazi file manager

-- Shell surfaces and tools
hl.bind(K(mod .. " + Space"),     hl.dsp.global("ryoku:launcher"))
hl.bind(K(mod .. " + L"),         hl.dsp.exec_cmd("ryoku-shell lock"))
hl.bind(K(mod .. " + Escape"),    hl.dsp.global("ryoku:quicksettings")) -- session actions live in quick settings
hl.bind(K(mod .. " + W"),         hl.dsp.global("ryoku:wallpaper-menu"))      -- wallpaper + theme menu (bottom-centre frame blob: scrolling images/live, colour filter, themes)
hl.bind(K(mod .. " + SHIFT + W"), hl.dsp.exec_cmd("ryoku-shell wallpaper random")) -- random wallpaper, random transition
hl.bind(K(mod .. " + SHIFT + V"), hl.dsp.exec_cmd("ryoku-summon ryovm flock -n -o /tmp/ryovm.lock qs -c ryovm")) -- ryovm: summon to current workspace
hl.bind(K(mod .. " + V"),         hl.dsp.global("ryoku:clipboard")) -- clipboard (sidebar deep link)
hl.bind(K(mod .. " + Tab"),       hl.dsp.global("ryoku:overview")) -- workspace overview (expo: live previews, drag windows between workspaces, cycle)
hl.bind(K(mod .. " + ALT + Tab"), hl.dsp.global("ryoku:overview")) -- workspace overview, stepping desktops (Alt+Tab again inside cycles desktops)
hl.bind(K(mod .. " + M"),         hl.dsp.global("ryoku:visualizer"))        -- toggle the desktop audio visualiser
hl.bind(K(mod .. " + SHIFT + M"), hl.dsp.global("ryoku:visualizer-overlay")) -- raise the visualiser over windows (flip back to desktop)
hl.bind(K(mod .. " + ALT + M"),   hl.dsp.global("ryoku:visualizer-place"))   -- grab the ring or orb and drag it where you want it
hl.bind(K(mod .. " + grave"),     hl.dsp.exec_cmd("ryoku-shell voice"))             -- tap: Voxtype speech-to-text + mic wave (tap again to stop)
hl.bind(K(mod .. " + comma"),     hl.dsp.exec_cmd("ryoku-shell hub open"))     -- ryoku settings
hl.bind(K(mod .. " + S"),         hl.dsp.global("ryoku:stash"))         -- Feature sidebar: screen time + downloads (Super+S)
hl.bind(K(mod .. " + SHIFT + S"), hl.dsp.exec_cmd("flock -n -o /tmp/ryoshot.lock qs -c ryoshot"))  -- ryoshot: beautify and annotate
hl.bind(K(mod .. " + SHIFT + C"), hl.dsp.exec_cmd("hyprpicker -a"))                 -- pick a color

-- Move/resize with the mouse
hl.bind(K(mod .. " + mouse:272"), hl.dsp.window.drag(),   { mouse = true })
hl.bind(K(mod .. " + mouse:273"), hl.dsp.window.resize(), { mouse = true })

-- Workspaces. Super+N focuses the Nth workspace OF THE CURRENT DESKTOP (a
-- desktop is a block of 10 workspace ids; see scripts/ryoku-workspace and the
-- overview). On desktop 2, Super+3 -> ws13, never ws3, so each desktop keeps its
-- own 1..10 and windows never jump desktops. The helper also pulls the target to
-- the monitor under the cursor, so the keys drive whichever screen the mouse is
-- on. Super+Alt+N sends the active window to that slot, staying on this desktop.
local ws_helper = (os.getenv("HOME") or "") .. "/.config/hypr/scripts/ryoku-workspace"

hl.bind(K(mod .. " + H"),          hl.dsp.exec_cmd(ws_helper .. " hide"))          -- hide the focused window in the scratchpad (press again on it to bring it back)
hl.bind(K(mod .. " + ALT + H"),    hl.dsp.workspace.toggle_special("scratch"))     -- show or hide the scratchpad (special workspace)
hl.bind(K(mod .. " + J"),          hl.dsp.workspace.toggle_special("music"))       -- toggle the music scratchpad (special workspace)
hl.bind(K(mod .. " + mouse_up"),   hl.dsp.focus({ workspace = "r-1" }))            -- previous workspace
hl.bind(K(mod .. " + mouse_down"), hl.dsp.focus({ workspace = "r+1" }))            -- next workspace
for i = 1, 10 do
    local key = i % 10 -- 10 maps to the 0 key
    hl.bind(K(mod .. " + " .. key),          hl.dsp.exec_cmd(ws_helper .. " focus " .. i)) -- focus slot i of the current desktop
    hl.bind(K(mod .. " + ALT + " .. key),    hl.dsp.exec_cmd(ws_helper .. " move " .. i))  -- send active window to slot i of the current desktop
end

-- Media and volume keys. ryoku-volume honours the volume panel's BOOST toggle
-- (Config.qsbar.audioBoost in shell.json): off = safe 100% cap, on = 150%.
hl.bind(K("XF86AudioRaiseVolume"), hl.dsp.exec_cmd("ryoku-volume up"),   { locked = true, repeating = true })
hl.bind(K("XF86AudioLowerVolume"), hl.dsp.exec_cmd("ryoku-volume down"), { locked = true, repeating = true })
hl.bind(K("XF86AudioMute"),        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true })
hl.bind(K("XF86AudioPlay"),        hl.dsp.exec_cmd("playerctl play-pause"),                           { locked = true })
hl.bind(K("XF86AudioNext"),        hl.dsp.exec_cmd("playerctl next"),                                 { locked = true })
hl.bind(K("XF86AudioPrev"),        hl.dsp.exec_cmd("playerctl previous"),                             { locked = true })
hl.bind(K(mod .. " + SHIFT + A"), hl.dsp.exec_cmd("ryoku-restart-audio")) -- recover audio when sound stops coming back

-- Brightness keys (laptop backlight + external DDC monitors)
hl.bind(K("XF86MonBrightnessUp"),   hl.dsp.exec_cmd("ryoku-cmd-brightness +5"), { locked = true, repeating = true })
hl.bind(K("XF86MonBrightnessDown"), hl.dsp.exec_cmd("ryoku-cmd-brightness -5"), { locked = true, repeating = true })

-- Touchpad lock (the FN touchpad key)
hl.bind(K("XF86TouchpadToggle"), hl.dsp.exec_cmd("ryoku-cmd-touchpad toggle"), { locked = true }) -- toggle the touchpad
hl.bind(K("XF86TouchpadOn"),     hl.dsp.exec_cmd("ryoku-cmd-touchpad on"),     { locked = true }) -- enable the touchpad
hl.bind(K("XF86TouchpadOff"),    hl.dsp.exec_cmd("ryoku-cmd-touchpad off"),    { locked = true }) -- disable the touchpad
