add_newline = true

format = """
$directory$git_branch$git_status
$character"""

[directory]
style = "bold blue"
truncation_length = 4

[git_branch]
symbol = " "
style = "bold purple"
format = " [$symbol$branch]($style)"

[git_status]
style = "bold red"
format = " [$all_status$ahead_behind]($style)"

[character]
success_symbol = "[Ω](bold green)"
error_symbol = "[Ω](bold red)"
vimcmd_symbol = "[Ω](bold yellow)"
